### ISSUE TITLE
Header does not display if you scroll down and back to the top without stopping

### ISSUE THREAD

**Issue by pnicholls** [dyang/DYFloatingHeaderView#1]
Hey nice little bit of code!

Just noticed a bug in the example where the header will not show if you quickly scroll down and back up to the top without stopping.

If i get time ill send through a pull request, cheers.

**Comment by dyang** [comment]
Hi Peter, thanks for reporting the issue.  Unfortunately I don't have extra bandwidth at this moment so it will be great if you can fix that and send me a pull request.  Thanks!

**Comment by nothingimportant55** [comment]
To anyone who has this problem, just add this in the #pragma mark - UIScrollViewDelegate section:
- (void)scrollViewDidEndDragging:(UIScrollView *)scrollView willDecelerate:(BOOL)willDecelerate {
  
  // if will decelerate is true, do nothing, as scrollViewDidEndDecelerating will be called
  // otherwise, react here because it´s a drag with a stationary stop
  if (willDecelerate == NO) {
  
  ```
  // scrolling has stopped, save position for restore
  [self.headerView scrollViewDidEndDecelerating:scrollView];
  ```
  
  }
  }
